### ISSUE TITLE
Investigar

### ISSUE THREAD

**Issue by AlejandroGorgues** [AlejandroGorgues/AstroTools#5]
- Astropy
- scipy
- qfitsview
- IRAF-splot
- https://jwst-docs.stsci.edu/jwst-post-pipeline-data-analysis
- Formatos de imágenes fits y asdf, y cómo manipularlos con python
-Librerias y paquetes de python del JWST: glue (IMPORTANTE), ginga, specviz y cubeviz

**Comment by AlvaroLabiano** [comment]
También formatos de imágenes y cómo manipularlas con python:
fits
asdf

**Comment by AlvaroLabiano** [comment]
pyfits (https://pyfits.readthedocs.io/en/latest/)
flujo, densidad de flujo, redshift, etc
