### ISSUE TITLE
Comprobrar funcionamiento

### ISSUE THREAD

**Issue by AlejandroGorgues** [AlejandroGorgues/AstroTools#7]
Comprobar que los programas "mrs_chan.py" y "mrs_spec_chan.py" compilan en otro ordenador.

**Comment by AlejandroGorgues** [comment]
conda create -n cubeviz01 -c glueviz cubeviz
conda  activate cubeviz01 
cubeviz o specviz
Comprobar en MAC

conda remove --name cubeviz01 --all

**Comment by AlvaroLabiano** [comment]
Me da un montón de errores y no se abren ni cubeviz ni specviz

**Comment by AlejandroGorgues** [comment]
[table1.zip](https://github.com/AlejandroGorgues/AstroTools/files/4159590/table1.zip)
